apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaUser
metadata:
  name: share-price-generator
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: prices
        operation: Write
      - resource:
          type: topic
          name: prices
        operation: Create
      - resource:
          type: topic
          name: prices
        operation: Describe
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaUser
metadata:
  name: share-position-generator
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
    - resource:
        type: topic
        name: positions
      operation: Write
    - resource:
        type: topic
        name: positions
      operation: Create
    - resource:
        type: topic
        name: positions
      operation: Describe
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaUser
metadata:
  name: share-position-aggregator
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
    - resource:
        type: topic
        name: portfolio
      operation: Write
    - resource:
        type: topic
        name: portfolio
      operation: Create
    - resource:
        type: topic
        name: portfolio
      operation: Describe
    - resource:
        type: topic
        name: positions
      operation: Read
    - resource:
        type: topic
        name: positions
      operation: Describe
    - resource:
        type: group
        name: positions
      operation: Read
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaUser
metadata:
  name: share-pricer
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
    - resource:
        type: topic
        name: priced-portfolio
      operation: Write
    - resource:
        type: topic
        name: priced-portfolio
      operation: Create
    - resource:
        type: topic
        name: priced-portfolio
      operation: Describe
    - resource:
        type: topic
        name: prices
      operation: Read
    - resource:
        type: topic
        name: prices
      operation: Describe
    - resource:
        type: topic
        name: portfolio
      operation: Read
    - resource:
        type: topic
        name: portfolio
      operation: Describe
    - resource:
        type: group
        name: pricer
      operation: Read
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaUser
metadata:
  name: share-portfolio-aggregator
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
    - resource:
        type: topic
        name: portfolio-value
      operation: Write
    - resource:
        type: topic
        name: portfolio-value
      operation: Create
    - resource:
        type: topic
        name: portfolio-value
      operation: Describe
    - resource:
        type: topic
        name: priced-portfolio
      operation: Read
    - resource:
        type: topic
        name: priced-portfolio
      operation: Describe
    - resource:
        type: group
        name: priced-portfolio
      operation: Read
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaUser
metadata:
  name: share-portfolio-value
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
    - resource:
        type: topic
        name: portfolio-value
      operation: Read
    - resource:
        type: topic
        name: portfolio-value
      operation: Describe
    - resource:
        type: group
        name: portfolio-value
      operation: Read
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: prices
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
  config:
      retention.bytes: 107374182
      retention.ms: 86400000
      segment.bytes: 107374182
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: positions
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.bytes: 107374182
    retention.ms: 86400000
    segment.bytes: 107374182
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: portfolio
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.bytes: 107374182
    retention.ms: 86400000
    segment.bytes: 107374182
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: priced-portfolio
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.bytes: 107374182
    retention.ms: 86400000
    segment.bytes: 107374182
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: portfolio-value
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.bytes: 107374182
    retention.ms: 86400000
    segment.bytes: 107374182
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: share-price-generator
  name: share-price-generator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: share-price-generator
    spec:
      containers:
      - name: share-price-generator
        image: quay.io/kafka-enablement-2020/share-price-generator:latest
        env:
          - name: CA_CRT
            valueFrom:
              secretKeyRef:
                name: my-cluster-cluster-ca-cert
                key: ca.crt
          - name: USER_CRT
            valueFrom:
              secretKeyRef:
                name: share-price-generator
                key: user.crt
          - name: USER_KEY
            valueFrom:
              secretKeyRef:
                name: share-price-generator
                key: user.key
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap:9093
          - name: TOPIC
            value: prices
          - name: TIMER
            value: "5000"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: share-position-generator
  name: share-position-generator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: share-position-generator
    spec:
      containers:
      - name: share-position-generator
        image: quay.io/kafka-enablement-2020/share-position-generator:latest
        env:
        - name: CA_CRT
          valueFrom:
            secretKeyRef:
              name: my-cluster-cluster-ca-cert
              key: ca.crt
        - name: USER_CRT
          valueFrom:
            secretKeyRef:
              name: share-position-generator
              key: user.crt
        - name: USER_KEY
          valueFrom:
            secretKeyRef:
              name: share-position-generator
              key: user.key
        - name: BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap:9093
        - name: TOPIC
          value: positions
        - name: TIMER
          value: "5000"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: position-aggregator
  name: position-aggregator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: position-aggregator
    spec:
      containers:
      - name: position-aggregator
        image: quay.io/kafka-enablement-2020/share-position-aggregator:latest
        env:
        - name: CA_CRT
          valueFrom:
            secretKeyRef:
              name: my-cluster-cluster-ca-cert
              key: ca.crt
        - name: USER_CRT
          valueFrom:
            secretKeyRef:
              name: share-position-aggregator
              key: user.crt
        - name: USER_KEY
          valueFrom:
            secretKeyRef:
              name: share-position-aggregator
              key: user.key
        - name: BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap:9093
        - name: SOURCE_TOPIC
          value: positions
        - name: TARGET_TOPIC
          value: portfolio
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pricer
  name: pricer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pricer
    spec:
      containers:
      - name: pricer
        image: quay.io/kafka-enablement-2020/share-pricer:latest
        env:
        - name: CA_CRT
          valueFrom:
            secretKeyRef:
              name: my-cluster-cluster-ca-cert
              key: ca.crt
        - name: USER_CRT
          valueFrom:
            secretKeyRef:
              name: share-pricer
              key: user.crt
        - name: USER_KEY
          valueFrom:
            secretKeyRef:
              name: share-pricer
              key: user.key
        - name: BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap:9093
        - name: LEFT_SOURCE_TOPIC
          value: portfolio
        - name: RIGHT_SOURCE_TOPIC
          value: prices
        - name: TARGET_TOPIC
          value: priced-portfolio
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: portfolio-aggregator
  name: portfolio-aggregator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: portfolio-aggregator
    spec:
      containers:
      - name: portfolio-aggregator
        image: quay.io/kafka-enablement-2020/share-portfolio-aggregator:latest
        env:
        - name: CA_CRT
          valueFrom:
            secretKeyRef:
              name: my-cluster-cluster-ca-cert
              key: ca.crt
        - name: USER_CRT
          valueFrom:
            secretKeyRef:
              name: share-portfolio-aggregator
              key: user.crt
        - name: USER_KEY
          valueFrom:
            secretKeyRef:
              name: share-portfolio-aggregator
              key: user.key
        - name: BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap:9093
        - name: SOURCE_TOPIC
          value: priced-portfolio
        - name: TARGET_TOPIC
          value: portfolio-value
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: portfolio-value
  name: portfolio-value
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: portfolio-value
    spec:
      containers:
      - name: portfolio-value
        image: quay.io/kafka-enablement-2020/share-portfolio-value:latest
        env:
        - name: CA_CRT
          valueFrom:
            secretKeyRef:
              name: my-cluster-cluster-ca-cert
              key: ca.crt
        - name: USER_CRT
          valueFrom:
            secretKeyRef:
              name: share-portfolio-value
              key: user.crt
        - name: USER_KEY
          valueFrom:
            secretKeyRef:
              name: share-portfolio-value
              key: user.key
        - name: BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap:9093
        - name: TOPIC
          value: portfolio-value
        - name: GROUP_ID
          value: portfolio-value